[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chess>=1.11.2",
    "python-dotenv>=1.1.1",
    "slack-bolt>=1.24.0",
]
